name: Test KinD

on: push

jobs:
    tests-with-kind:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            
            - name: Setup Helm
              uses: azure/setup-helm@v3
              with:
                version: v3.12.1

            - name: Runner IP
              id: runnerIp
              run: |
                RUNNER_IP=$(curl https://api.ipify.org)
                echo $RUNNER_IP
                sed -i "s/HOST_IP/$RUNNER_IP/g" ./ci/kind.config.yaml
            
            - name: Create KinD cluster
              uses: helm/kind-action@v1.8.0
              with:
                config: ./ci/kind.config.yaml

            - name: Load docker images
              run: |
                docker pull ghcr.io/projectcapsule/capsule
                kind load docker-image ghcr.io/projectcapsule/capsule:latest \
                    --name chart-testing

                docker pull clastix/kubectl:v1.28
                kind load docker-image clastix/kubectl:v1.28 \
                    --name chart-testing

            - name: Install capsule
              run: |
                helm repo add projectcapsule https://projectcapsule.github.io/charts
                helm install capsule projectcapsule/capsule \
                    -n capsule-system \
                    --create-namespace \
                    --version=0.6.0 \
                    --debug \
                    --timeout 10m

                kubectl get deploy -n capsule-system

            - name: Test install tenant
              run: |
                echo <<EOF
                  apiVersion: capsule.clastix.io/v1beta2
                  kind: Tenant
                  metadata:
                    annotations:
                      tenant.test.aca.org/name: test-tenant
                    labels:
                      tenant.test.aca.org/name: testTenant
                    name: test-tenant
                  spec:
                    namespaceOptions:
                      quota: 5
                EOF | kubectl apply -f -
                
                kubectl wait --for=jsonpath'{.status.state}'=Active \
                  tenant/tenant-test \
                  --timeout=300s \
                  --ojsonpath='{.status}' | jq